-- ---------------------------------------------------------------------------------------------------------------------
--
-- LINEAR
--
-- ---------------------------------------------------------------------------------------------------------------------
-- [ LQ1 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE{
        ?researchGroups lubm:subOrganizationOf ?department .
        ?department lubm:name "Department1" .
}

-- [ LQ2 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE{
        ?department lubm:subOrganizationOf ?university .
        ?professor lubm:worksFor ?department .
        ?student lubm:advisor ?professor .
        ?student lubm:memberOf <http://www.Department1.University0.edu> .
}

-- [ LQ3 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE{
        ?resgroup lubm:subOrganizationOf ?department .
        ?professor lubm:worksFor ?department .
        ?student lubm:advisor ?professor .
        ?student lubm:memberOf <http://www.Department1.University0.edu> .
}

-- [ LQ4 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE{
        ?advisor lubm:emailAddress ?email .
        ?advisor lubm:worksFor ?department .
        ?department lubm:name "Department1" .
}


-- ---------------------------------------------------------------------------------------------------------------------
--
-- STAR
--
-- ---------------------------------------------------------------------------------------------------------------------

-- [ LQ5 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE{
        ?student lubm:advisor ?advisor .
        ?student lubm:name ?name .
        ?student lubm:undergraduateDegreeFrom ?university .
        ?student lubm:takesCourse <http://www.Department1.University0.edu/GraduateCourse33> .
}

-- [ LQ6 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE {
        ?professor lubm:emailAddress ?mail .
        ?professor lubm:telephone ?phone .
        ?professor lubm:doctoralDegreeFrom ?doctor .
        ?professor lubm:name "FullProfessor1" .
}

-- [ LQ7 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE {
        ?student  lubm:memberOf  ?department .
        ?student  lubm:takesCourse  ?course .
        ?student  lubm:advisor ?advisor .
        ?student  lubm:teachingAssistantOf  ?tacourse .
        ?student  lubm:emailAddress ?email .
        ?student  lubm:name ?name .
        ?student  lubm:telephone ?telephone .
        ?student  lubm:undergraduateDegreeFrom <http://www.University0.edu> .
}

-- [ LQ8 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE {
        ?student  lubm:memberOf  ?department .
        ?student  lubm:takesCourse  ?course .
        ?student  lubm:advisor ?advisor .
        ?student  lubm:teachingAssistantOf  ?tacourse .
        ?student  lubm:emailAddress ?email .
        ?student  lubm:name "GraduateStudent71" .
        ?student  lubm:telephone ?telephone .
        ?student  lubm:undergraduateDegreeFrom ?university .
}

-- ---------------------------------------------------------------------------------------------------------------------
--
-- FLAKE
--
-- ---------------------------------------------------------------------------------------------------------------------

-- [ LQ9 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE {
        ?student lubm:advisor ?advisor .
        ?advisor lubm:worksFor ?department .
        ?department lubm:subOrganizationOf ?university .
        ?student lubm:name ?name .
        ?student lubm:telephone ?tel .
        ?student lubm:takesCourse <http://www.Department12.University1.edu/Course1> .
}

-- [ LQ10 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE {
        ?department lubm:name ?name .
        ?resgroup lubm:subOrganizationOf ?department .
        ?department lubm:subOrganizationOf <http://www.University0.edu> .
        ?student lubm:memberOf ?department .
        ?student lubm:advisor ?professor .
        ?student lubm:takesCourse ?course .
}

-- [ LQ11 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE {
        ?department lubm:name ?name .
        ?resgroup lubm:subOrganizationOf ?department .
        ?department lubm:subOrganizationOf ?university .
        ?student lubm:memberOf ?department .
        ?student lubm:advisor ?professor .
        ?student lubm:takesCourse <http://www.Department1.University0.edu/GraduateCourse33> .
}

-- ---------------------------------------------------------------------------------------------------------------------
--
-- COMPLEX
--
-- ---------------------------------------------------------------------------------------------------------------------

-- [ LQ12 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE {
        ?department lubm:subOrganizationOf ?university .
        ?resgroup lubm:subOrganizationOf ?department .
        ?student lubm:memberOf ?department .
        ?department lubm:name ?name .
        ?student lubm:advisor ?professor .
        ?publication lubm:publicationAuthor ?professor .
        ?publication lubm:publicationAuthor <http://www.Department1.University10.edu/AssociateProfessor1>.
}

-- [ LQ13 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE {
        ?department lubm:subOrganizationOf ?university .
        ?resgroup lubm:subOrganizationOf ?department .
        ?student lubm:memberOf ?department .
        ?student lubm:advisor ?professor .
        ?student lubm:takesCourse ?course .
        ?publication lubm:publicationAuthor ?professor .
        ?publication lubm:publicationAuthor <http://www.Department1.University10.edu/AssociateProfessor1> .
        ?publication lubm:name ?title .
}

-- [ LQ14 ]
PREFIX lubm: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT *
WHERE{
        ?student lubm:advisor ?advisor .
        ?advisor lubm:worksFor ?department .
        ?department lubm:subOrganizationOf <http://www.University0.edu> .
        ?head lubm:headOf ?department .
        ?head lubm:emailAddress ?email .
        ?head lubm:doctoralDegreeFrom ?alma .
        ?student lubm:name ?name .
        ?student lubm:telephone ?tel .
        ?student lubm:takesCourse ?course .
}
